# Use an official Maven runtime as a parent image
FROM maven:3.8.4-openjdk-21

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . .

# Build your application with Maven
RUN mvn clean install

# Specify the command to run on container startup
CMD ["java", "-jar", "target/rental-0.0.1-SNAPSHOT.jar"]
