# Spring application settings
app:
  name: rental-project

# Server settings
server:
  port: 8080

# Logging settings
log:
  level:
    org:
      springframework: INFO  # Set to INFO for production

# Data Source settings
db:
  datasource:
    url: jdbc:mysql://localhost:3308/rentalproject  # Replace with your production database URL
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Z@v010ka  # Use a secure password
  h2:
    console:
      enabled: false  # Disable H2 console in production
  jpa:
    hibernate:
      ddl-auto: validate  # Use "validate" for production, or "none" to disable automatic schema updates
    show-sql: false  # Set to false in production

# Thymeleaf settings
view:
  thymeleaf:
    cache: true  # Enable template caching for better performance

# Spring Security settings (customize as per your requirements)
spring:
  security:
    basic:
      enabled: false  # Disable basic authentication if not needed
    # Add more security configurations as required

# Externalize sensitive information using environment variables
# Example: DB_PASSWORD should be set as an environment variable

