# Spring application settings
spring:
  application:
    name: rental-project

# Server settings
server:
  port: 8080

# Logging settings
logging:
  level:
    org:
      springframework: DEBUG

# Data Source settings
datasource:
  url: jdbc:h2:mem:testdb
  driver-class-name: org.h2.Driver
  username: sa
  password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# Thymeleaf settings
thymeleaf:
  cache: false
